name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Run create metricts classic
      - uses: tanawat011/metrics@master
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: github-metrics-classic.svg

      # Run create metricts habits
      - uses: tanawat011/metrics@master
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: github-metrics-habits.svg
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no

      # Run create metricts wakatime
      - uses: tanawat011/metrics@master
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: github-metrics-wakatime.svg
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
