name: Waka Readme

on:
  schedule: [{cron: "0 0 * * *"}]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-readme-wakatime:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Run wakatime
      - uses: tanawat011/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          TIME_RANGE: last_year
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          SHOW_TOTAL: true
