name: Waka Readme

on:
  # (optional) Run workflow manually
  workflow_dispatch:
  # Schedule daily updates
  schedule: [{cron: "* * * * *"}]
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/wakatime.yml
        # - uses: tanawat011/tanawat011@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          API_BASE_URL: https://wakapi.dev/api
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
